### ISSUE TITLE
cropped window with remote desktop

### ISSUE THREAD

**Issue by BrBella** [weizhenFrank/DeepPhospho#3]
Dear Developers,

I would like to run DeepPhospho but with remote desktop control (the only way to access the computer) the lower part of the window is not visible so I can not start the run (picture attached). The IT said this is an issue because of the remote control. 
Is there any way to run DeepPhospho in this mode?
Thank you very much in advance!
Bella

![on_MSmonster](https://user-images.githubusercontent.com/105847667/169247803-bf3c6c22-9d79-4d63-82ad-80a2b7e58058.png)
.

**Comment by gureann** [comment]
Hi Bella, 

Sorry for the late reply.

I have just added an option to set the sizes of window and font in the commit 8c496d9. You can download the source code and overwrite the old files to use it . And if you have change some code or configs, just overwrite these two files is ok: desktop_app.py in main folder, and ui_wx.py in /deep_phospho/desktop_app/

You can find it in the top-left manu
![图片](https://user-images.githubusercontent.com/48235800/171998877-04baad89-d4b9-4068-8d78-74259b600b1e.png)

I'd suggest change fontsize to a comfortable value and set window height to 1, because the window height has a min value which depends on fontsize.

Hope this will be helpful, and if it works please let me know. I'll create a new release in this version.

Best,
Ronghui
