### ISSUE TITLE
Reporting error when training with format EasyPQP

### ISSUE THREAD

**Issue by Vectolyser** [weizhenFrank/DeepPhospho#8]
Hello, when I used training data generated by FragPipe, DeepPhospho reports an error "Error for task". How can I solve this? Please see the error log attached.Thanks!
[RunnerLog.txt](https://github.com/weizhenFrank/DeepPhospho/files/11584208/RunnerLog.txt)

**Comment by gureann** [comment]
Hi @Vectolyser ,
Thanks for reporting this. 

The problem was caused by the transformation function for library from FragPipe to inner format, and incorrectly converted files didn't pass further check.
Sorry for the error that has taken your time. I have published a new release to fix it. Please find them here: https://github.com/weizhenFrank/DeepPhospho/releases/tag/20230528
I'd recommand to download `DeepPhospho-20230528.zip`, and copy the folder `DeepPhosphoPythonEnv` from your old version to the main folder of this new version.

And it will be better to delete previously generated files in folder `DeepPhosphoDesktop` to avoid the reuse of some caches from your previous running. 

Ronghui

**Comment by Vectolyser** [comment]
> Hi @Vectolyser , Thanks for reporting this.
> 
> The problem was caused by the transformation function for library from FragPipe to inner format, and incorrectly converted files didn't pass further check. Sorry for the error that has taken your time. I have published a new release to fix it. Please find them here: https://github.com/weizhenFrank/DeepPhospho/releases/tag/20230528 I'd recommand to download `DeepPhospho-20230528.zip`, and copy the folder `DeepPhosphoPythonEnv` from your old version to the main folder of this new version.
> 
> And it will be better to delete previously generated files in folder `DeepPhosphoDesktop` to avoid the reuse of some caches from your previous running.
> 
> Ronghui
[RunnerLog.txt](https://github.com/weizhenFrank/DeepPhospho/files/11595411/RunnerLog.txt)

Thanks. It works on my laptop(RTX 3060), but still report error on my another computer(RTX 2080Ti), please have a look.

**Comment by gureann** [comment]
Glad to hear it works on your laptop.

In the log file you posted, it shows `RuntimeError: CUDA error: unspecified launch failure`.  I haven't seen the error before. Refer to the information from some forums, it might be caused by driver or pytorch.

Could you please check your CUDA version at first, with `nvcc -V`, and to confirm if it's version 10.1, since the environment we provided in the release uses pytorch 1.7+CUDA 10.1.
If you have multiple CUDA versions installed, on Windows, you can use `ls env:` in powershell or check this folder `C:\Program Files\NVIDIA GPU Computing Toolkit\`.

If you have different CUDA version installed, install 10.1 will solve this problem. If you don't want to install such an old driver, 11.7 would be a good choice, and I'll release an enviroment uses this version later.

**Comment by Vectolyser** [comment]
> Glad to hear it works on your laptop.
> 
> In the log file you posted, it shows `RuntimeError: CUDA error: unspecified launch failure`. I haven't seen the error before. Refer to the information from some forums, it might be caused by driver or pytorch.
> 
> Could you please check your CUDA version at first, with `nvcc -V`, and to confirm if it's version 10.1, since the environment we provided in the release uses pytorch 1.7+CUDA 10.1. If you have multiple CUDA versions installed, on Windows, you can use `ls env:` in powershell or check this folder `C:\Program Files\NVIDIA GPU Computing Toolkit\`.
> 
> If you have different CUDA version installed, install 10.1 will solve this problem. If you don't want to install such an old driver, 11.7 would be a good choice, and I'll release an enviroment uses this version later.
I have switched my CUDA version to 10.1 and resolved the issue. Thank you for your help!

**Comment by Vectolyser** [comment]
1
